#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Samples.Resource", IsApplication=true)]

namespace Samples
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circleColor = global::Samples.Resource.Attribute.circleColor;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circularProgressBarStyle = global::Samples.Resource.Attribute.circularProgressBarStyle;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_gravity = global::Samples.Resource.Attribute.circular_gravity;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_indeterminate = global::Samples.Resource.Attribute.circular_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_indeterminate_interval = global::Samples.Resource.Attribute.circular_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_marker_progress = global::Samples.Resource.Attribute.circular_marker_progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress = global::Samples.Resource.Attribute.circular_progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress_background_color = global::Samples.Resource.Attribute.circular_progress_background_color;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress_color = global::Samples.Resource.Attribute.circular_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_stroke_width = global::Samples.Resource.Attribute.circular_stroke_width;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.indeterminate = global::Samples.Resource.Attribute.indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.indeterminate_interval = global::Samples.Resource.Attribute.indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.innerSize = global::Samples.Resource.Attribute.innerSize;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.max = global::Samples.Resource.Attribute.max;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.pinned = global::Samples.Resource.Attribute.pinned;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.pinnedDrawable = global::Samples.Resource.Attribute.pinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progress = global::Samples.Resource.Attribute.progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progressButtonStyle = global::Samples.Resource.Attribute.progressButtonStyle;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progressColor = global::Samples.Resource.Attribute.progressColor;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.shadowDrawable = global::Samples.Resource.Attribute.shadowDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.unpinnedDrawable = global::Samples.Resource.Attribute.unpinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Color.progress_default_circle_color = global::Samples.Resource.Color.progress_default_circle_color;
			global::com.refractored.monodroidtoolkit.Resource.Color.progress_default_progress_color = global::Samples.Resource.Color.progress_default_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_dark = global::Samples.Resource.Color.refractored_background_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_holo_dark = global::Samples.Resource.Color.refractored_background_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_holo_light = global::Samples.Resource.Color.refractored_background_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_light = global::Samples.Resource.Color.refractored_background_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_dark = global::Samples.Resource.Color.refractored_bright_foreground_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_dark_disabled = global::Samples.Resource.Color.refractored_bright_foreground_dark_disabled;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_disabled_holo_dark = global::Samples.Resource.Color.refractored_bright_foreground_disabled_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_disabled_holo_light = global::Samples.Resource.Color.refractored_bright_foreground_disabled_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_holo_dark = global::Samples.Resource.Color.refractored_bright_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_holo_light = global::Samples.Resource.Color.refractored_bright_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_light = global::Samples.Resource.Color.refractored_bright_foreground_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_disabled_holo_dark = global::Samples.Resource.Color.refractored_dim_foreground_disabled_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_disabled_holo_light = global::Samples.Resource.Color.refractored_dim_foreground_disabled_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_holo_dark = global::Samples.Resource.Color.refractored_dim_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_holo_light = global::Samples.Resource.Color.refractored_dim_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_highlighted_text_holo_dark = global::Samples.Resource.Color.refractored_highlighted_text_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_highlighted_text_holo_light = global::Samples.Resource.Color.refractored_highlighted_text_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_hint_foreground_holo_dark = global::Samples.Resource.Color.refractored_hint_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_hint_foreground_holo_light = global::Samples.Resource.Color.refractored_hint_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_bright = global::Samples.Resource.Color.refractored_holo_blue_bright;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_dark = global::Samples.Resource.Color.refractored_holo_blue_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_light = global::Samples.Resource.Color.refractored_holo_blue_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_green_dark = global::Samples.Resource.Color.refractored_holo_green_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_green_light = global::Samples.Resource.Color.refractored_holo_green_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_orange_dark = global::Samples.Resource.Color.refractored_holo_orange_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_orange_light = global::Samples.Resource.Color.refractored_holo_orange_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_purple = global::Samples.Resource.Color.refractored_holo_purple;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_red_dark = global::Samples.Resource.Color.refractored_holo_red_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_red_light = global::Samples.Resource.Color.refractored_holo_red_light;
			global::com.refractored.monodroidtoolkit.Resource.Dimension.progress_inner_size = global::Samples.Resource.Dimension.progress_inner_size;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_pinned = global::Samples.Resource.Drawable.pin_progress_pinned;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_shadow = global::Samples.Resource.Drawable.pin_progress_shadow;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_unpinned = global::Samples.Resource.Drawable.pin_progress_unpinned;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.scrubber_control_normal_holo = global::Samples.Resource.Drawable.scrubber_control_normal_holo;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.scrubber_control_pressed_holo = global::Samples.Resource.Drawable.scrubber_control_pressed_holo;
			global::com.refractored.monodroidtoolkit.Resource.Id.bottom = global::Samples.Resource.Id.bottom;
			global::com.refractored.monodroidtoolkit.Resource.Id.center = global::Samples.Resource.Id.center;
			global::com.refractored.monodroidtoolkit.Resource.Id.center_horizontal = global::Samples.Resource.Id.center_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.center_vertical = global::Samples.Resource.Id.center_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip = global::Samples.Resource.Id.clip;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip_horizontal = global::Samples.Resource.Id.clip_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip_vertical = global::Samples.Resource.Id.clip_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.end = global::Samples.Resource.Id.end;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill = global::Samples.Resource.Id.fill;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill_horizontal = global::Samples.Resource.Id.fill_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill_vertical = global::Samples.Resource.Id.fill_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.left = global::Samples.Resource.Id.left;
			global::com.refractored.monodroidtoolkit.Resource.Id.right = global::Samples.Resource.Id.right;
			global::com.refractored.monodroidtoolkit.Resource.Id.start = global::Samples.Resource.Id.start;
			global::com.refractored.monodroidtoolkit.Resource.Id.top = global::Samples.Resource.Id.top;
			global::com.refractored.monodroidtoolkit.Resource.Integer.circular_indeterminent_interval = global::Samples.Resource.Integer.circular_indeterminent_interval;
			global::com.refractored.monodroidtoolkit.Resource.Integer.progressbutton_indeterminent_interval = global::Samples.Resource.Integer.progressbutton_indeterminent_interval;
			global::com.refractored.monodroidtoolkit.Resource.Style.CircularProgressBar = global::Samples.Resource.Style.CircularProgressBar;
			global::com.refractored.monodroidtoolkit.Resource.Style.CircularProgressBarLight = global::Samples.Resource.Style.CircularProgressBarLight;
			global::com.refractored.monodroidtoolkit.Resource.Style.ProgressButton = global::Samples.Resource.Style.ProgressButton;
			global::com.refractored.monodroidtoolkit.Resource.Style.ProgressButton_Pin = global::Samples.Resource.Style.ProgressButton_Pin;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar = global::Samples.Resource.Styleable.HoloCircularProgressBar;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_gravity = global::Samples.Resource.Styleable.HoloCircularProgressBar_circular_gravity;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate = global::Samples.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate_interval = global::Samples.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_marker_progress = global::Samples.Resource.Styleable.HoloCircularProgressBar_circular_marker_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress = global::Samples.Resource.Styleable.HoloCircularProgressBar_circular_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress_background_color = global::Samples.Resource.Styleable.HoloCircularProgressBar_circular_progress_background_color;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress_color = global::Samples.Resource.Styleable.HoloCircularProgressBar_circular_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_stroke_width = global::Samples.Resource.Styleable.HoloCircularProgressBar_circular_stroke_width;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton = global::Samples.Resource.Styleable.ProgressButton;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_clickable = global::Samples.Resource.Styleable.ProgressButton_android_clickable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_focusable = global::Samples.Resource.Styleable.ProgressButton_android_focusable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_selectableItemBackground = global::Samples.Resource.Styleable.ProgressButton_android_selectableItemBackground;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_circleColor = global::Samples.Resource.Styleable.ProgressButton_circleColor;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_indeterminate = global::Samples.Resource.Styleable.ProgressButton_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_indeterminate_interval = global::Samples.Resource.Styleable.ProgressButton_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_innerSize = global::Samples.Resource.Styleable.ProgressButton_innerSize;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_max = global::Samples.Resource.Styleable.ProgressButton_max;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_pinned = global::Samples.Resource.Styleable.ProgressButton_pinned;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_pinnedDrawable = global::Samples.Resource.Styleable.ProgressButton_pinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_progress = global::Samples.Resource.Styleable.ProgressButton_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_progressColor = global::Samples.Resource.Styleable.ProgressButton_progressColor;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_shadowDrawable = global::Samples.Resource.Styleable.ProgressButton_shadowDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_unpinnedDrawable = global::Samples.Resource.Styleable.ProgressButton_unpinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.Theme = global::Samples.Resource.Styleable.Theme;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.Theme_circularProgressBarStyle = global::Samples.Resource.Styleable.Theme_circularProgressBarStyle;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int circleColor = 2130771971;
			
			// aapt resource value: 0x7f010014
			public const int circularProgressBarStyle = 2130771988;
			
			// aapt resource value: 0x7f01000c
			public const int circular_gravity = 2130771980;
			
			// aapt resource value: 0x7f010012
			public const int circular_indeterminate = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int circular_indeterminate_interval = 2130771987;
			
			// aapt resource value: 0x7f01000f
			public const int circular_marker_progress = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int circular_progress = 2130771982;
			
			// aapt resource value: 0x7f010011
			public const int circular_progress_background_color = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int circular_progress_color = 2130771984;
			
			// aapt resource value: 0x7f01000d
			public const int circular_stroke_width = 2130771981;
			
			// aapt resource value: 0x7f01000a
			public const int indeterminate = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int indeterminate_interval = 2130771979;
			
			// aapt resource value: 0x7f010008
			public const int innerSize = 2130771976;
			
			// aapt resource value: 0x7f010002
			public const int max = 2130771970;
			
			// aapt resource value: 0x7f010009
			public const int pinned = 2130771977;
			
			// aapt resource value: 0x7f010005
			public const int pinnedDrawable = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int progress = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int progressButtonStyle = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int progressColor = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int shadowDrawable = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int unpinnedDrawable = 2130771974;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05001f
			public const int background_dark = 2131034143;
			
			// aapt resource value: 0x7f050024
			public const int background_holo_dark = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int background_holo_light = 2131034149;
			
			// aapt resource value: 0x7f050020
			public const int background_light = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int bright_foreground_dark = 2131034145;
			
			// aapt resource value: 0x7f050023
			public const int bright_foreground_dark_disabled = 2131034147;
			
			// aapt resource value: 0x7f050028
			public const int bright_foreground_disabled_holo_dark = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int bright_foreground_disabled_holo_light = 2131034153;
			
			// aapt resource value: 0x7f050026
			public const int bright_foreground_holo_dark = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int bright_foreground_holo_light = 2131034151;
			
			// aapt resource value: 0x7f050022
			public const int bright_foreground_light = 2131034146;
			
			// aapt resource value: 0x7f05002b
			public const int dim_foreground_disabled_holo_dark = 2131034155;
			
			// aapt resource value: 0x7f05002e
			public const int dim_foreground_disabled_holo_light = 2131034158;
			
			// aapt resource value: 0x7f05002a
			public const int dim_foreground_holo_dark = 2131034154;
			
			// aapt resource value: 0x7f05002d
			public const int dim_foreground_holo_light = 2131034157;
			
			// aapt resource value: 0x7f050030
			public const int highlighted_text_holo_dark = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int highlighted_text_holo_light = 2131034161;
			
			// aapt resource value: 0x7f05002c
			public const int hint_foreground_holo_dark = 2131034156;
			
			// aapt resource value: 0x7f05002f
			public const int hint_foreground_holo_light = 2131034159;
			
			// aapt resource value: 0x7f05003b
			public const int holo_blue_bright = 2131034171;
			
			// aapt resource value: 0x7f050035
			public const int holo_blue_dark = 2131034165;
			
			// aapt resource value: 0x7f050032
			public const int holo_blue_light = 2131034162;
			
			// aapt resource value: 0x7f050036
			public const int holo_green_dark = 2131034166;
			
			// aapt resource value: 0x7f050033
			public const int holo_green_light = 2131034163;
			
			// aapt resource value: 0x7f05003a
			public const int holo_orange_dark = 2131034170;
			
			// aapt resource value: 0x7f050039
			public const int holo_orange_light = 2131034169;
			
			// aapt resource value: 0x7f050038
			public const int holo_purple = 2131034168;
			
			// aapt resource value: 0x7f050037
			public const int holo_red_dark = 2131034167;
			
			// aapt resource value: 0x7f050034
			public const int holo_red_light = 2131034164;
			
			// aapt resource value: 0x7f050000
			public const int progress_default_circle_color = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int progress_default_progress_color = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int refractored_background_dark = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int refractored_background_holo_dark = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int refractored_background_holo_light = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int refractored_background_light = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int refractored_bright_foreground_dark = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int refractored_bright_foreground_dark_disabled = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int refractored_bright_foreground_disabled_holo_dark = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int refractored_bright_foreground_disabled_holo_light = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int refractored_bright_foreground_holo_dark = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int refractored_bright_foreground_holo_light = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int refractored_bright_foreground_light = 2131034117;
			
			// aapt resource value: 0x7f05000e
			public const int refractored_dim_foreground_disabled_holo_dark = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int refractored_dim_foreground_disabled_holo_light = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int refractored_dim_foreground_holo_dark = 2131034125;
			
			// aapt resource value: 0x7f050010
			public const int refractored_dim_foreground_holo_light = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int refractored_highlighted_text_holo_dark = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int refractored_highlighted_text_holo_light = 2131034132;
			
			// aapt resource value: 0x7f05000f
			public const int refractored_hint_foreground_holo_dark = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int refractored_hint_foreground_holo_light = 2131034130;
			
			// aapt resource value: 0x7f05001e
			public const int refractored_holo_blue_bright = 2131034142;
			
			// aapt resource value: 0x7f050018
			public const int refractored_holo_blue_dark = 2131034136;
			
			// aapt resource value: 0x7f050015
			public const int refractored_holo_blue_light = 2131034133;
			
			// aapt resource value: 0x7f050019
			public const int refractored_holo_green_dark = 2131034137;
			
			// aapt resource value: 0x7f050016
			public const int refractored_holo_green_light = 2131034134;
			
			// aapt resource value: 0x7f05001d
			public const int refractored_holo_orange_dark = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int refractored_holo_orange_light = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int refractored_holo_purple = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int refractored_holo_red_dark = 2131034138;
			
			// aapt resource value: 0x7f050017
			public const int refractored_holo_red_light = 2131034135;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int progress_inner_size = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int standard_padding = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_card = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background_holo_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int pin_progress_pinned = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int pin_progress_shadow = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int pin_progress_unpinned = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int scrubber_control_normal_holo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int scrubber_control_pressed_holo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int seattle = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int bottom = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int center = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int center_horizontal = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int center_vertical = 2130968579;
			
			// aapt resource value: 0x7f040015
			public const int circular_progress_bar = 2130968597;
			
			// aapt resource value: 0x7f040004
			public const int clip = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int clip_horizontal = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int clip_vertical = 2130968582;
			
			// aapt resource value: 0x7f040025
			public const int container = 2130968613;
			
			// aapt resource value: 0x7f040007
			public const int end = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int fill = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int fill_horizontal = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int fill_vertical = 2130968586;
			
			// aapt resource value: 0x7f040018
			public const int hide_ui = 2130968600;
			
			// aapt resource value: 0x7f04000f
			public const int holoCircularProgressBar1 = 2130968591;
			
			// aapt resource value: 0x7f040011
			public const int image = 2130968593;
			
			// aapt resource value: 0x7f040017
			public const int image_loader = 2130968599;
			
			// aapt resource value: 0x7f04000b
			public const int left = 2130968587;
			
			// aapt resource value: 0x7f040013
			public const int main_layout = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int name = 2130968594;
			
			// aapt resource value: 0x7f040019
			public const int network = 2130968601;
			
			// aapt resource value: 0x7f040021
			public const int pin_progress_1 = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int pin_progress_2 = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int pin_progress_3 = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int pin_progress_4 = 2130968612;
			
			// aapt resource value: 0x7f040014
			public const int progress_button = 2130968596;
			
			// aapt resource value: 0x7f040020
			public const int progress_seek_bar = 2130968608;
			
			// aapt resource value: 0x7f04000c
			public const int right = 2130968588;
			
			// aapt resource value: 0x7f040016
			public const int scale_image = 2130968598;
			
			// aapt resource value: 0x7f04000d
			public const int start = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int switch_theme = 2130968592;
			
			// aapt resource value: 0x7f04001a
			public const int textView1 = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int textView2 = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int textView3 = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int textView4 = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int textView5 = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int textView6 = 2130968607;
			
			// aapt resource value: 0x7f04000e
			public const int top = 2130968590;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070001
			public const int circular_indeterminent_interval = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int progressbutton_indeterminent_interval = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int circular_progress_bar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Friend = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ImageLoader = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Network = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int progress_button = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ScaleImage = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090001
			public const int ApplicationName = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int Hello = 2131296256;
			
			// aapt resource value: 0x7f090003
			public const int circular_progress_bar = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int content_desc_pinned_downloaded = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int content_desc_pinned_downloading = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int content_desc_pinned_not_downloaded = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int content_desc_unpinned_downloaded = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int content_desc_unpinned_downloading = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int content_desc_unpinned_not_downloaded = 2131296265;
			
			// aapt resource value: 0x7f09000d
			public const int hide_ui = 2131296269;
			
			// aapt resource value: 0x7f09000c
			public const int image_loader = 2131296268;
			
			// aapt resource value: 0x7f09000e
			public const int network = 2131296270;
			
			// aapt resource value: 0x7f090002
			public const int progress_button = 2131296258;
			
			// aapt resource value: 0x7f09000b
			public const int scale_image = 2131296267;
			
			// aapt resource value: 0x7f09000a
			public const int switch_theme = 2131296266;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f08000c
			public const int AlertThemeDark = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int AlertThemeLight = 2131230731;
			
			// aapt resource value: 0x7f080002
			public const int CircularProgressBar = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int CircularProgressBarLight = 2131230723;
			
			// aapt resource value: 0x7f08000e
			public const int ExpandableListViewStyle = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int ListViewStyle = 2131230733;
			
			// aapt resource value: 0x7f080009
			public const int MyTheme = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int MyThemeDark = 2131230730;
			
			// aapt resource value: 0x7f080000
			public const int ProgressButton = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int ProgressButton_1 = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int ProgressButton_2 = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int ProgressButton_Clickable = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int ProgressButton_Clickable_3 = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int ProgressButton_Clickable_4 = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int ProgressButton_Pin = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] HoloCircularProgressBar = new int[]
			{
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 0
			public const int HoloCircularProgressBar_circular_gravity = 0;
			
			// aapt resource value: 6
			public const int HoloCircularProgressBar_circular_indeterminate = 6;
			
			// aapt resource value: 7
			public const int HoloCircularProgressBar_circular_indeterminate_interval = 7;
			
			// aapt resource value: 3
			public const int HoloCircularProgressBar_circular_marker_progress = 3;
			
			// aapt resource value: 2
			public const int HoloCircularProgressBar_circular_progress = 2;
			
			// aapt resource value: 5
			public const int HoloCircularProgressBar_circular_progress_background_color = 5;
			
			// aapt resource value: 4
			public const int HoloCircularProgressBar_circular_progress_color = 4;
			
			// aapt resource value: 1
			public const int HoloCircularProgressBar_circular_stroke_width = 1;
			
			public static int[] ProgressButton = new int[]
			{
					16842970,
					16842981,
					16843534,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 1
			public const int ProgressButton_android_clickable = 1;
			
			// aapt resource value: 0
			public const int ProgressButton_android_focusable = 0;
			
			// aapt resource value: 2
			public const int ProgressButton_android_selectableItemBackground = 2;
			
			// aapt resource value: 5
			public const int ProgressButton_circleColor = 5;
			
			// aapt resource value: 12
			public const int ProgressButton_indeterminate = 12;
			
			// aapt resource value: 13
			public const int ProgressButton_indeterminate_interval = 13;
			
			// aapt resource value: 10
			public const int ProgressButton_innerSize = 10;
			
			// aapt resource value: 4
			public const int ProgressButton_max = 4;
			
			// aapt resource value: 11
			public const int ProgressButton_pinned = 11;
			
			// aapt resource value: 7
			public const int ProgressButton_pinnedDrawable = 7;
			
			// aapt resource value: 3
			public const int ProgressButton_progress = 3;
			
			// aapt resource value: 6
			public const int ProgressButton_progressColor = 6;
			
			// aapt resource value: 9
			public const int ProgressButton_shadowDrawable = 9;
			
			// aapt resource value: 8
			public const int ProgressButton_unpinnedDrawable = 8;
			
			public static int[] Theme = new int[]
			{
					2130771988};
			
			// aapt resource value: 0
			public const int Theme_circularProgressBarStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
