#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("com.refractored.monodroidtoolkit.Resource", IsApplication=true)]

namespace com.refractored.monodroidtoolkit
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int circleColor = 2130771971;
			
			// aapt resource value: 0x7f010014
			public const int circularProgressBarStyle = 2130771988;
			
			// aapt resource value: 0x7f01000c
			public const int circular_gravity = 2130771980;
			
			// aapt resource value: 0x7f010012
			public const int circular_indeterminate = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int circular_indeterminate_interval = 2130771987;
			
			// aapt resource value: 0x7f01000f
			public const int circular_marker_progress = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int circular_progress = 2130771982;
			
			// aapt resource value: 0x7f010011
			public const int circular_progress_background_color = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int circular_progress_color = 2130771984;
			
			// aapt resource value: 0x7f01000d
			public const int circular_stroke_width = 2130771981;
			
			// aapt resource value: 0x7f01000a
			public const int indeterminate = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int indeterminate_interval = 2130771979;
			
			// aapt resource value: 0x7f010008
			public const int innerSize = 2130771976;
			
			// aapt resource value: 0x7f010002
			public const int max = 2130771970;
			
			// aapt resource value: 0x7f010009
			public const int pinned = 2130771977;
			
			// aapt resource value: 0x7f010005
			public const int pinnedDrawable = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int progress = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int progressButtonStyle = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int progressColor = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int shadowDrawable = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int unpinnedDrawable = 2130771974;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030000
			public const int progress_default_circle_color = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int progress_default_progress_color = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int refractored_background_dark = 2130903042;
			
			// aapt resource value: 0x7f030007
			public const int refractored_background_holo_dark = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int refractored_background_holo_light = 2130903048;
			
			// aapt resource value: 0x7f030003
			public const int refractored_background_light = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int refractored_bright_foreground_dark = 2130903044;
			
			// aapt resource value: 0x7f030006
			public const int refractored_bright_foreground_dark_disabled = 2130903046;
			
			// aapt resource value: 0x7f03000b
			public const int refractored_bright_foreground_disabled_holo_dark = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int refractored_bright_foreground_disabled_holo_light = 2130903052;
			
			// aapt resource value: 0x7f030009
			public const int refractored_bright_foreground_holo_dark = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int refractored_bright_foreground_holo_light = 2130903050;
			
			// aapt resource value: 0x7f030005
			public const int refractored_bright_foreground_light = 2130903045;
			
			// aapt resource value: 0x7f03000e
			public const int refractored_dim_foreground_disabled_holo_dark = 2130903054;
			
			// aapt resource value: 0x7f030011
			public const int refractored_dim_foreground_disabled_holo_light = 2130903057;
			
			// aapt resource value: 0x7f03000d
			public const int refractored_dim_foreground_holo_dark = 2130903053;
			
			// aapt resource value: 0x7f030010
			public const int refractored_dim_foreground_holo_light = 2130903056;
			
			// aapt resource value: 0x7f030013
			public const int refractored_highlighted_text_holo_dark = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int refractored_highlighted_text_holo_light = 2130903060;
			
			// aapt resource value: 0x7f03000f
			public const int refractored_hint_foreground_holo_dark = 2130903055;
			
			// aapt resource value: 0x7f030012
			public const int refractored_hint_foreground_holo_light = 2130903058;
			
			// aapt resource value: 0x7f03001e
			public const int refractored_holo_blue_bright = 2130903070;
			
			// aapt resource value: 0x7f030018
			public const int refractored_holo_blue_dark = 2130903064;
			
			// aapt resource value: 0x7f030015
			public const int refractored_holo_blue_light = 2130903061;
			
			// aapt resource value: 0x7f030019
			public const int refractored_holo_green_dark = 2130903065;
			
			// aapt resource value: 0x7f030016
			public const int refractored_holo_green_light = 2130903062;
			
			// aapt resource value: 0x7f03001d
			public const int refractored_holo_orange_dark = 2130903069;
			
			// aapt resource value: 0x7f03001c
			public const int refractored_holo_orange_light = 2130903068;
			
			// aapt resource value: 0x7f03001b
			public const int refractored_holo_purple = 2130903067;
			
			// aapt resource value: 0x7f03001a
			public const int refractored_holo_red_dark = 2130903066;
			
			// aapt resource value: 0x7f030017
			public const int refractored_holo_red_light = 2130903063;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int progress_inner_size = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int pin_progress_pinned = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int pin_progress_shadow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int pin_progress_unpinned = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int scrubber_control_normal_holo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int scrubber_control_pressed_holo = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int bottom = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int center = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int center_horizontal = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int center_vertical = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int clip = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int clip_horizontal = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int clip_vertical = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int end = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int fill = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int fill_horizontal = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int fill_vertical = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int left = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int right = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int start = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int top = 2131165198;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050001
			public const int circular_indeterminent_interval = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int progressbutton_indeterminent_interval = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int CircularProgressBar = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int CircularProgressBarLight = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int ProgressButton = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int ProgressButton_Pin = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] HoloCircularProgressBar = new int[]
			{
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 0
			public const int HoloCircularProgressBar_circular_gravity = 0;
			
			// aapt resource value: 6
			public const int HoloCircularProgressBar_circular_indeterminate = 6;
			
			// aapt resource value: 7
			public const int HoloCircularProgressBar_circular_indeterminate_interval = 7;
			
			// aapt resource value: 3
			public const int HoloCircularProgressBar_circular_marker_progress = 3;
			
			// aapt resource value: 2
			public const int HoloCircularProgressBar_circular_progress = 2;
			
			// aapt resource value: 5
			public const int HoloCircularProgressBar_circular_progress_background_color = 5;
			
			// aapt resource value: 4
			public const int HoloCircularProgressBar_circular_progress_color = 4;
			
			// aapt resource value: 1
			public const int HoloCircularProgressBar_circular_stroke_width = 1;
			
			public static int[] ProgressButton = new int[]
			{
					16842970,
					16842981,
					16843534,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 1
			public const int ProgressButton_android_clickable = 1;
			
			// aapt resource value: 0
			public const int ProgressButton_android_focusable = 0;
			
			// aapt resource value: 2
			public const int ProgressButton_android_selectableItemBackground = 2;
			
			// aapt resource value: 5
			public const int ProgressButton_circleColor = 5;
			
			// aapt resource value: 12
			public const int ProgressButton_indeterminate = 12;
			
			// aapt resource value: 13
			public const int ProgressButton_indeterminate_interval = 13;
			
			// aapt resource value: 10
			public const int ProgressButton_innerSize = 10;
			
			// aapt resource value: 4
			public const int ProgressButton_max = 4;
			
			// aapt resource value: 11
			public const int ProgressButton_pinned = 11;
			
			// aapt resource value: 7
			public const int ProgressButton_pinnedDrawable = 7;
			
			// aapt resource value: 3
			public const int ProgressButton_progress = 3;
			
			// aapt resource value: 6
			public const int ProgressButton_progressColor = 6;
			
			// aapt resource value: 9
			public const int ProgressButton_shadowDrawable = 9;
			
			// aapt resource value: 8
			public const int ProgressButton_unpinnedDrawable = 8;
			
			public static int[] Theme = new int[]
			{
					2130771988};
			
			// aapt resource value: 0
			public const int Theme_circularProgressBarStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
