#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("com.refractored.monodroidtoolkit.Resource", IsApplication=false)]

namespace com.refractored.monodroidtoolkit
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public static int circleColor = 2130771971;
			
			// aapt resource value: 0x7f010014
			public static int circularProgressBarStyle = 2130771988;
			
			// aapt resource value: 0x7f01000c
			public static int circular_gravity = 2130771980;
			
			// aapt resource value: 0x7f010012
			public static int circular_indeterminate = 2130771986;
			
			// aapt resource value: 0x7f010013
			public static int circular_indeterminate_interval = 2130771987;
			
			// aapt resource value: 0x7f01000f
			public static int circular_marker_progress = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public static int circular_progress = 2130771982;
			
			// aapt resource value: 0x7f010011
			public static int circular_progress_background_color = 2130771985;
			
			// aapt resource value: 0x7f010010
			public static int circular_progress_color = 2130771984;
			
			// aapt resource value: 0x7f01000d
			public static int circular_stroke_width = 2130771981;
			
			// aapt resource value: 0x7f01000a
			public static int indeterminate = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public static int indeterminate_interval = 2130771979;
			
			// aapt resource value: 0x7f010008
			public static int innerSize = 2130771976;
			
			// aapt resource value: 0x7f010002
			public static int max = 2130771970;
			
			// aapt resource value: 0x7f010009
			public static int pinned = 2130771977;
			
			// aapt resource value: 0x7f010005
			public static int pinnedDrawable = 2130771973;
			
			// aapt resource value: 0x7f010001
			public static int progress = 2130771969;
			
			// aapt resource value: 0x7f010000
			public static int progressButtonStyle = 2130771968;
			
			// aapt resource value: 0x7f010004
			public static int progressColor = 2130771972;
			
			// aapt resource value: 0x7f010007
			public static int shadowDrawable = 2130771975;
			
			// aapt resource value: 0x7f010006
			public static int unpinnedDrawable = 2130771974;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public static int progress_default_circle_color = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int progress_default_progress_color = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int refractored_background_dark = 2130968578;
			
			// aapt resource value: 0x7f040007
			public static int refractored_background_holo_dark = 2130968583;
			
			// aapt resource value: 0x7f040008
			public static int refractored_background_holo_light = 2130968584;
			
			// aapt resource value: 0x7f040003
			public static int refractored_background_light = 2130968579;
			
			// aapt resource value: 0x7f040004
			public static int refractored_bright_foreground_dark = 2130968580;
			
			// aapt resource value: 0x7f040006
			public static int refractored_bright_foreground_dark_disabled = 2130968582;
			
			// aapt resource value: 0x7f04000b
			public static int refractored_bright_foreground_disabled_holo_dark = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public static int refractored_bright_foreground_disabled_holo_light = 2130968588;
			
			// aapt resource value: 0x7f040009
			public static int refractored_bright_foreground_holo_dark = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public static int refractored_bright_foreground_holo_light = 2130968586;
			
			// aapt resource value: 0x7f040005
			public static int refractored_bright_foreground_light = 2130968581;
			
			// aapt resource value: 0x7f04000e
			public static int refractored_dim_foreground_disabled_holo_dark = 2130968590;
			
			// aapt resource value: 0x7f040011
			public static int refractored_dim_foreground_disabled_holo_light = 2130968593;
			
			// aapt resource value: 0x7f04000d
			public static int refractored_dim_foreground_holo_dark = 2130968589;
			
			// aapt resource value: 0x7f040010
			public static int refractored_dim_foreground_holo_light = 2130968592;
			
			// aapt resource value: 0x7f040013
			public static int refractored_highlighted_text_holo_dark = 2130968595;
			
			// aapt resource value: 0x7f040014
			public static int refractored_highlighted_text_holo_light = 2130968596;
			
			// aapt resource value: 0x7f04000f
			public static int refractored_hint_foreground_holo_dark = 2130968591;
			
			// aapt resource value: 0x7f040012
			public static int refractored_hint_foreground_holo_light = 2130968594;
			
			// aapt resource value: 0x7f04001e
			public static int refractored_holo_blue_bright = 2130968606;
			
			// aapt resource value: 0x7f040018
			public static int refractored_holo_blue_dark = 2130968600;
			
			// aapt resource value: 0x7f040015
			public static int refractored_holo_blue_light = 2130968597;
			
			// aapt resource value: 0x7f040019
			public static int refractored_holo_green_dark = 2130968601;
			
			// aapt resource value: 0x7f040016
			public static int refractored_holo_green_light = 2130968598;
			
			// aapt resource value: 0x7f04001d
			public static int refractored_holo_orange_dark = 2130968605;
			
			// aapt resource value: 0x7f04001c
			public static int refractored_holo_orange_light = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public static int refractored_holo_purple = 2130968603;
			
			// aapt resource value: 0x7f04001a
			public static int refractored_holo_red_dark = 2130968602;
			
			// aapt resource value: 0x7f040017
			public static int refractored_holo_red_light = 2130968599;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public static int progress_inner_size = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int pin_progress_pinned = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int pin_progress_shadow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int pin_progress_unpinned = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int scrubber_control_normal_holo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int scrubber_control_pressed_holo = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f030000
			public static int bottom = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int center = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int center_horizontal = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int center_vertical = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int clip = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int clip_horizontal = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int clip_vertical = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int end = 2130903047;
			
			// aapt resource value: 0x7f030008
			public static int fill = 2130903048;
			
			// aapt resource value: 0x7f030009
			public static int fill_horizontal = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public static int fill_vertical = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public static int left = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public static int right = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public static int start = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public static int top = 2130903054;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060001
			public static int circular_indeterminent_interval = 2131099649;
			
			// aapt resource value: 0x7f060000
			public static int progressbutton_indeterminent_interval = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070002
			public static int CircularProgressBar = 2131165186;
			
			// aapt resource value: 0x7f070003
			public static int CircularProgressBarLight = 2131165187;
			
			// aapt resource value: 0x7f070000
			public static int ProgressButton = 2131165184;
			
			// aapt resource value: 0x7f070001
			public static int ProgressButton_Pin = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] HoloCircularProgressBar = new int[] {
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 0
			public static int HoloCircularProgressBar_circular_gravity = 0;
			
			// aapt resource value: 6
			public static int HoloCircularProgressBar_circular_indeterminate = 6;
			
			// aapt resource value: 7
			public static int HoloCircularProgressBar_circular_indeterminate_interval = 7;
			
			// aapt resource value: 3
			public static int HoloCircularProgressBar_circular_marker_progress = 3;
			
			// aapt resource value: 2
			public static int HoloCircularProgressBar_circular_progress = 2;
			
			// aapt resource value: 5
			public static int HoloCircularProgressBar_circular_progress_background_color = 5;
			
			// aapt resource value: 4
			public static int HoloCircularProgressBar_circular_progress_color = 4;
			
			// aapt resource value: 1
			public static int HoloCircularProgressBar_circular_stroke_width = 1;
			
			public static int[] ProgressButton = new int[] {
					16842970,
					16842981,
					16843534,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 1
			public static int ProgressButton_android_clickable = 1;
			
			// aapt resource value: 0
			public static int ProgressButton_android_focusable = 0;
			
			// aapt resource value: 2
			public static int ProgressButton_android_selectableItemBackground = 2;
			
			// aapt resource value: 5
			public static int ProgressButton_circleColor = 5;
			
			// aapt resource value: 12
			public static int ProgressButton_indeterminate = 12;
			
			// aapt resource value: 13
			public static int ProgressButton_indeterminate_interval = 13;
			
			// aapt resource value: 10
			public static int ProgressButton_innerSize = 10;
			
			// aapt resource value: 4
			public static int ProgressButton_max = 4;
			
			// aapt resource value: 11
			public static int ProgressButton_pinned = 11;
			
			// aapt resource value: 7
			public static int ProgressButton_pinnedDrawable = 7;
			
			// aapt resource value: 3
			public static int ProgressButton_progress = 3;
			
			// aapt resource value: 6
			public static int ProgressButton_progressColor = 6;
			
			// aapt resource value: 9
			public static int ProgressButton_shadowDrawable = 9;
			
			// aapt resource value: 8
			public static int ProgressButton_unpinnedDrawable = 8;
			
			public static int[] Theme = new int[] {
					2130771988};
			
			// aapt resource value: 0
			public static int Theme_circularProgressBarStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
